//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri2.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="K2TaskItem", Namespace="http://tempuri2.org/")]
    public partial class K2TaskItem : object
    {
        
        private ServiceReference.ArrayOfString ActionsField;
        
        private string IDField;
        
        private string serialNumberField;
        
        private string statusField;
        
        private string FolioField;
        
        private string ProcessInstanceIdField;
        
        private string TaskLinkField;
        
        private string TaskStatusField;
        
        private string TaskOwnerField;
        
        private string InternalEmployeeNameWithPrefixField;
        
        private string EmployeeNameField;
        
        private string EmployeeNameEnField;
        
        private string DepartmentNameField;
        
        private string DepartmentNameEnField;
        
        private string InternalServiceNameField;
        
        private string ServiceNameField;
        
        private string ServiceNameEnField;
        
        private System.DateTime RequestDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference.ArrayOfString Actions
        {
            get
            {
                return this.ActionsField;
            }
            set
            {
                this.ActionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string serialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Folio
        {
            get
            {
                return this.FolioField;
            }
            set
            {
                this.FolioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ProcessInstanceId
        {
            get
            {
                return this.ProcessInstanceIdField;
            }
            set
            {
                this.ProcessInstanceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TaskLink
        {
            get
            {
                return this.TaskLinkField;
            }
            set
            {
                this.TaskLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TaskStatus
        {
            get
            {
                return this.TaskStatusField;
            }
            set
            {
                this.TaskStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TaskOwner
        {
            get
            {
                return this.TaskOwnerField;
            }
            set
            {
                this.TaskOwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string InternalEmployeeNameWithPrefix
        {
            get
            {
                return this.InternalEmployeeNameWithPrefixField;
            }
            set
            {
                this.InternalEmployeeNameWithPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string EmployeeName
        {
            get
            {
                return this.EmployeeNameField;
            }
            set
            {
                this.EmployeeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string EmployeeNameEn
        {
            get
            {
                return this.EmployeeNameEnField;
            }
            set
            {
                this.EmployeeNameEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DepartmentNameEn
        {
            get
            {
                return this.DepartmentNameEnField;
            }
            set
            {
                this.DepartmentNameEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string InternalServiceName
        {
            get
            {
                return this.InternalServiceNameField;
            }
            set
            {
                this.InternalServiceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ServiceNameEn
        {
            get
            {
                return this.ServiceNameEnField;
            }
            set
            {
                this.ServiceNameEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime RequestDate
        {
            get
            {
                return this.RequestDateField;
            }
            set
            {
                this.RequestDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri2.org/", ConfigurationName="ServiceReference.TaskActionSoap")]
    public interface TaskActionSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/TaskActionsList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.TaskActionsListResponse> TaskActionsListAsync(ServiceReference.TaskActionsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/StartProcess", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.StartProcessResponse> StartProcessAsync(ServiceReference.StartProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/ActionWorklistItem", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.ActionWorklistItemResponse> ActionWorklistItemAsync(ServiceReference.ActionWorklistItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/GetEmployeeTaskList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetEmployeeTaskListResponse> GetEmployeeTaskListAsync(ServiceReference.GetEmployeeTaskListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TaskActionsListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TaskActionsList", Namespace="http://tempuri2.org/", Order=0)]
        public ServiceReference.TaskActionsListRequestBody Body;
        
        public TaskActionsListRequest()
        {
        }
        
        public TaskActionsListRequest(ServiceReference.TaskActionsListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class TaskActionsListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string serialNumber;
        
        public TaskActionsListRequestBody()
        {
        }
        
        public TaskActionsListRequestBody(string userName, string serialNumber)
        {
            this.userName = userName;
            this.serialNumber = serialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TaskActionsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TaskActionsListResponse", Namespace="http://tempuri2.org/", Order=0)]
        public ServiceReference.TaskActionsListResponseBody Body;
        
        public TaskActionsListResponse()
        {
        }
        
        public TaskActionsListResponse(ServiceReference.TaskActionsListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class TaskActionsListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.ArrayOfString TaskActionsListResult;
        
        public TaskActionsListResponseBody()
        {
        }
        
        public TaskActionsListResponseBody(ServiceReference.ArrayOfString TaskActionsListResult)
        {
            this.TaskActionsListResult = TaskActionsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartProcess", Namespace="http://tempuri2.org/", Order=0)]
        public ServiceReference.StartProcessRequestBody Body;
        
        public StartProcessRequest()
        {
        }
        
        public StartProcessRequest(ServiceReference.StartProcessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class StartProcessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int TableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int GeneralRequesID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProcessName;
        
        public StartProcessRequestBody()
        {
        }
        
        public StartProcessRequestBody(string userName, int TableID, int GeneralRequesID, string ProcessName)
        {
            this.userName = userName;
            this.TableID = TableID;
            this.GeneralRequesID = GeneralRequesID;
            this.ProcessName = ProcessName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartProcessResponse", Namespace="http://tempuri2.org/", Order=0)]
        public ServiceReference.StartProcessResponseBody Body;
        
        public StartProcessResponse()
        {
        }
        
        public StartProcessResponse(ServiceReference.StartProcessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class StartProcessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int StartProcessResult;
        
        public StartProcessResponseBody()
        {
        }
        
        public StartProcessResponseBody(int StartProcessResult)
        {
            this.StartProcessResult = StartProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActionWorklistItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActionWorklistItem", Namespace="http://tempuri2.org/", Order=0)]
        public ServiceReference.ActionWorklistItemRequestBody Body;
        
        public ActionWorklistItemRequest()
        {
        }
        
        public ActionWorklistItemRequest(ServiceReference.ActionWorklistItemRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class ActionWorklistItemRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userNameWithPrefix;
        
        public ActionWorklistItemRequestBody()
        {
        }
        
        public ActionWorklistItemRequestBody(string serialNumber, string action, string userNameWithPrefix)
        {
            this.serialNumber = serialNumber;
            this.action = action;
            this.userNameWithPrefix = userNameWithPrefix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActionWorklistItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActionWorklistItemResponse", Namespace="http://tempuri2.org/", Order=0)]
        public ServiceReference.ActionWorklistItemResponseBody Body;
        
        public ActionWorklistItemResponse()
        {
        }
        
        public ActionWorklistItemResponse(ServiceReference.ActionWorklistItemResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class ActionWorklistItemResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActionWorklistItemResult;
        
        public ActionWorklistItemResponseBody()
        {
        }
        
        public ActionWorklistItemResponseBody(bool ActionWorklistItemResult)
        {
            this.ActionWorklistItemResult = ActionWorklistItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeTaskListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeTaskList", Namespace="http://tempuri2.org/", Order=0)]
        public ServiceReference.GetEmployeeTaskListRequestBody Body;
        
        public GetEmployeeTaskListRequest()
        {
        }
        
        public GetEmployeeTaskListRequest(ServiceReference.GetEmployeeTaskListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class GetEmployeeTaskListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNameWithPrefix;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchPattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string employeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string employeeNameEn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string departmentName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string departmentNameEn;
        
        public GetEmployeeTaskListRequestBody()
        {
        }
        
        public GetEmployeeTaskListRequestBody(string userNameWithPrefix, string searchPattern, string employeeName, string employeeNameEn, string departmentName, string departmentNameEn)
        {
            this.userNameWithPrefix = userNameWithPrefix;
            this.searchPattern = searchPattern;
            this.employeeName = employeeName;
            this.employeeNameEn = employeeNameEn;
            this.departmentName = departmentName;
            this.departmentNameEn = departmentNameEn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeTaskListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeTaskListResponse", Namespace="http://tempuri2.org/", Order=0)]
        public ServiceReference.GetEmployeeTaskListResponseBody Body;
        
        public GetEmployeeTaskListResponse()
        {
        }
        
        public GetEmployeeTaskListResponse(ServiceReference.GetEmployeeTaskListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class GetEmployeeTaskListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.K2TaskItem[] GetEmployeeTaskListResult;
        
        public GetEmployeeTaskListResponseBody()
        {
        }
        
        public GetEmployeeTaskListResponseBody(ServiceReference.K2TaskItem[] GetEmployeeTaskListResult)
        {
            this.GetEmployeeTaskListResult = GetEmployeeTaskListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TaskActionSoapChannel : ServiceReference.TaskActionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TaskActionSoapClient : System.ServiceModel.ClientBase<ServiceReference.TaskActionSoap>, ServiceReference.TaskActionSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaskActionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TaskActionSoapClient.GetBindingForEndpoint(endpointConfiguration), TaskActionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskActionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaskActionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskActionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaskActionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskActionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.TaskActionsListResponse> ServiceReference.TaskActionSoap.TaskActionsListAsync(ServiceReference.TaskActionsListRequest request)
        {
            return base.Channel.TaskActionsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.TaskActionsListResponse> TaskActionsListAsync(string userName, string serialNumber)
        {
            ServiceReference.TaskActionsListRequest inValue = new ServiceReference.TaskActionsListRequest();
            inValue.Body = new ServiceReference.TaskActionsListRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.serialNumber = serialNumber;
            return ((ServiceReference.TaskActionSoap)(this)).TaskActionsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.StartProcessResponse> ServiceReference.TaskActionSoap.StartProcessAsync(ServiceReference.StartProcessRequest request)
        {
            return base.Channel.StartProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.StartProcessResponse> StartProcessAsync(string userName, int TableID, int GeneralRequesID, string ProcessName)
        {
            ServiceReference.StartProcessRequest inValue = new ServiceReference.StartProcessRequest();
            inValue.Body = new ServiceReference.StartProcessRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.TableID = TableID;
            inValue.Body.GeneralRequesID = GeneralRequesID;
            inValue.Body.ProcessName = ProcessName;
            return ((ServiceReference.TaskActionSoap)(this)).StartProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ActionWorklistItemResponse> ServiceReference.TaskActionSoap.ActionWorklistItemAsync(ServiceReference.ActionWorklistItemRequest request)
        {
            return base.Channel.ActionWorklistItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ActionWorklistItemResponse> ActionWorklistItemAsync(string serialNumber, string action, string userNameWithPrefix)
        {
            ServiceReference.ActionWorklistItemRequest inValue = new ServiceReference.ActionWorklistItemRequest();
            inValue.Body = new ServiceReference.ActionWorklistItemRequestBody();
            inValue.Body.serialNumber = serialNumber;
            inValue.Body.action = action;
            inValue.Body.userNameWithPrefix = userNameWithPrefix;
            return ((ServiceReference.TaskActionSoap)(this)).ActionWorklistItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetEmployeeTaskListResponse> ServiceReference.TaskActionSoap.GetEmployeeTaskListAsync(ServiceReference.GetEmployeeTaskListRequest request)
        {
            return base.Channel.GetEmployeeTaskListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetEmployeeTaskListResponse> GetEmployeeTaskListAsync(string userNameWithPrefix, string searchPattern, string employeeName, string employeeNameEn, string departmentName, string departmentNameEn)
        {
            ServiceReference.GetEmployeeTaskListRequest inValue = new ServiceReference.GetEmployeeTaskListRequest();
            inValue.Body = new ServiceReference.GetEmployeeTaskListRequestBody();
            inValue.Body.userNameWithPrefix = userNameWithPrefix;
            inValue.Body.searchPattern = searchPattern;
            inValue.Body.employeeName = employeeName;
            inValue.Body.employeeNameEn = employeeNameEn;
            inValue.Body.departmentName = departmentName;
            inValue.Body.departmentNameEn = departmentNameEn;
            return ((ServiceReference.TaskActionSoap)(this)).GetEmployeeTaskListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaskActionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TaskActionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaskActionSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://demo.adaaapps.com:5001/taskactions.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TaskActionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://demo.adaaapps.com:5001/taskactions.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TaskActionSoap,
            
            TaskActionSoap12,
        }
    }
}
